### ISSUE TITLE
Fix error

### ISSUE THREAD

**Issue by chriskrycho** [toranb/ember-fetch-tsdefs#1]
Given how we're using it (faking the module import), I think the definition can reasonably be simplified to look like this:

```ts
// Type definitions for Ember Fetch
// Project: https://github.com/stefanpenner/ember-fetch
// Definitions by: Toran Billups <https://github.com/toranb>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

export default function fetch(input: RequestInfo, init?: RequestInit): Promise<Response>;
```

**Comment by toranb** [comment]
@chriskrycho seems to work w/ TypeScript v2.6

https://github.com/toranb/ember-redux-yelp/commits/branches/seamlessAndTypeScript

edit: ah you are trying to simplify this it seems ;) in that case .. this repo is dead for now after `ember-fetch` (the addon) pulled in a PR for the typedefs :)

**Comment by chriskrycho** [comment]
Oh, did they? Sweet; I missed seeing that; will update accordingly in my app tomorrow.

Maybe mark this repo as deprecated in that case?

**Comment by chriskrycho** [comment]
Never mind; you already did!
